<?php
    //echo '<div id="partial-navigation-bottom">';

    // loop root level (only has Home, but later may have an Admin root page?)
    foreach ($this->container as $page) {
        // check if it is active (not recursive)
        $isActive = $page->isActive(false);
        $liClass = $isActive ? ' class="active"' : '';
        if ($page->_label !== null) {
        	echo '<li ' . $liClass . '><h4>' . $this->menu()->htmlify($page) . '</h4></li>', PHP_EOL;
        }
        // loop next level
        foreach ($page as $page) {
            // check if it is active (recursive)
            $isActive = $page->isActive(true);
            $liClass = $isActive ? ' class="active"' : '';
            echo '<li ' . $liClass . '><h4>' . $this->menu()->htmlify($page) . '</h4></li>', PHP_EOL;
        }
    }
    //echo '</div>';
?>