<?php if (sizeof($this->pages)==0) return ; ?>

<?php
for ($i = 0, $size = sizeof($this->pages); $i < $size; $i++) {
    // @see Zend_Navigation_Page_Mvc
    $url   = $this->pages[$i]->getHref();
    $label = $this->pages[$i]->getLabel();

    if ($label) {
        if ($i != ($size - 1)) {
            echo "<a href='$url' title='$label'>$label</a> &raquo; ";
        } else {
            echo $label;
        }
    }
}
?>
