<div class="footer">
    <div class="cont_width">
        <div class="footer_logo">&nbsp;</div>
        <div>
            <ul>
                <li><h4>Home</h4></li>
                <li>
                    <?php
                        echo $this->navigation()
                            ->menu($this->menuContainer('Home'))
                            ->setPartial('/default/partial/bottomMenu.phtml')
                            ->setMaxDepth(50)
                            ->setMinDepth(0);
                    ?>
                </li>
            </ul>
            <ul>
                <li><h4>Terms of use</h4></li>
                <li>
                    <?php
                    echo $this->navigation()
                        ->menu($this->menuContainer('Terms of use'))
                        ->setPartial('/default/partial/bottomMenu.phtml')
                        ->setMaxDepth(50)
                        ->setMinDepth(0);
                    ?>
                </li>
            </ul>
        </div>
        <div class="clear">
            &#169; Copyright <?php echo date('Y') ?> <a href="http://nixsolutions.com" title="NIX Solutions Ltd.">NIX Solutions Ltd.</a>
        </div>
    </div>
</div>