<div class="header">
    <div class="cont_width">
        <div class="logo">
            <h1><a href="/" title="Homepage">Core</a></h1>
            <h2>Content Management Framework</h2>
        </div>
        <div class="menu small"></div>
        <div class="menu clearright">
            <?php
            echo $this->menu('Home', 0, 50, '/default/partial/mainMenu.phtml');
            ?>
            <br class="clear"/>
        </div>
    </div>
    <div class="topgreen clear">
        <div class="cont_width">
            <?php
            echo $this->menu('Home', 0, 10, '/default/partial/breadcrumbs.phtml','breadcrumbs');
            ?>
        </div>
    </div>
    <div class="tophelp">
        <div class="cont_width">
            <div class="simpleMenu">
                <br class="clear"/>
            </div>
            Here goes help text
        </div>
    </div>
</div>