<?php

$this->headLink(array('rel' => 'shortcut icon', 'href' => $this->baseUrl('/favicon.ico'), 'type' => 'image/x-icon'), 'PREPEND')
   ->prependStylesheet($this->baseUrl('layouts/default/css/style.css'));

$this->headScript()
    ->prependFile($this->baseUrl('scripts/jquery/jquery.js?ver=1.4.2'))
    ->appendFile($this->baseUrl('layouts/default/scripts/ui.js'));

?>
<head>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headTitle()->setSeparator(': ') ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <base href="<?php echo $this->baseUrl() ?>"/>
</head>