<div class="header">
    <div class="cont_width">
        <div class="logo">
            <h1><a href="/" title="Homepage">Core</a></h1>
            <h2>Content Management Framework</h2>
        </div>
        <div class="menu small"></div>
        <div class="menu clearright">
            <?php
                echo $this->navigation($this->menuContainer('Home'))
                ->menu()
                ->setPartial('/default/partial/mainMenu.phtml')
                ->setMaxDepth(10)
                ->setMinDepth(0);
            ?>
            <br class="clear"/>
        </div>
    </div>
    <div class="topgreen clear">
        <div class="cont_width">
            <?php
            echo $this->navigation($this->menuContainer('Home'))
                ->breadcrumbs()
                ->setPartial('/default/partial/breadcrumbs.phtml')
                ->setMaxDepth(10)
                ->setMinDepth(0);
            ?>
        </div>
    </div>
    <div class="tophelp">
        <div class="cont_width">
            <div class="simpleMenu">
                <br class="clear"/>
            </div>
            Here goes help text
        </div>
    </div>
</div>