<?php

$this->headLink(array(
    'rel' => 'shortcut icon',
    'href' => $this->baseUrl('/favicon.ico'),
    'type' => 'image/x-icon'
));

$this->asset();

?>
<head>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headTitle()->setSeparator(': ') ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <base href="<?php echo $this->baseUrl() ?>"/>
</head>