<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="/">Core</a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li class="active"></li>
                    <li class="dropdown" id="menu-tests">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#menu-tests">
                            Tests
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="<?=$this->url(array('module'=>'tests', 'controller'=>'index', 'action' => 'controls'))?>">Controls</a></li>
                            <li><a href="<?=$this->url(array('module'=>'tests', 'controller'=>'index', 'action' => 'markup'))?>">Markup</a></li>
                        </ul>
                    </li>
                </ul>
                <? if (false) : ?>
                    <p class="navbar-text pull-right">
                        <?php /*echo $this->__('Logged in as %s', ($this->url('users', 'profile') ?'': $identity->login))*/?>
                        (<?=$this->url(array('module'=>'users', 'controller'=> 'login', 'action' => 'logout'))?>)
                    </p>
                <? else: ?>
                <ul class="nav pull-right">
                    <li><a href="<?=$this->url(array('module'=>'users', 'controller'=>'login', 'action' => 'index'))?>">Login</a></li>
                </ul>
                <? endif; ?>
                <div id="loading"></div>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>

