<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="/">Core</a>
            <div class="nav-collapse pull-right">
                <?php
                    echo $this->navigation($this->menuContainer('Home'))
                    ->menu()
                    ->setPartial('/default/partial/main.phtml')
                    ->setMaxDepth(10)
                    ->setMinDepth(0);
                ?>
                <div id="loading"></div>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>

