<ul class="nav nav-list">
<?php
    foreach ($this->container as $pages) {
        // loop next level
        foreach ($pages as $page) {
            // check if it is active (not recursive)
            $liClass = array();

            if ($page->isActive(false)) {
                $liClass[] = 'active';
            }

            if (!$page->getHref()) {
                $liClass[] = 'nav-header';
            }

            if ($page->_label !== null && $page->isVisible(true)) {
                echo '<li class="' . join(' ', $liClass) . '">' . $this->menu()->htmlify($page) . '</li>', PHP_EOL;
            }

            if ($page->_pages) {
                foreach ($page as $page) {
                    // check if it is active (recursive)
                    $isActive = $page->isActive(true);
                    $liClass = $isActive ? ' class="active"' : '';
                    if ($page->_label !== null && $page->isVisible(true)) {
                        echo '<li ' . $liClass . '>' . $this->menu()->htmlify($page);
                        echo '</li>', PHP_EOL;
                    }
                }
            }

        }
    }
?>
</ul>