<head>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headTitle()->setSeparator(': ') ?>
    <link rel="profile" href="http://gmpg.org/xfn/11"/>
    <link rel="shortcut icon" type="image/x-icon" href="<?=$this->baseUrl('favicon.ico')?>" />
    <link rel="stylesheet" href="<?=$this->baseUrl('/css/dashboard.css')?>" />
    <link rel="stylesheet" href="<?=$this->baseUrl('/css/bootstrap.css')?>" />
    <link rel="stylesheet" href="<?=$this->baseUrl('/css/jquery-ui.css')?>" />
    <script src="<?=$this->baseUrl('/js/jquery/jquery.js')?>" ></script>
    <script src="<?=$this->baseUrl('/js/bootstrap.js')?>" ></script>
    <script src="<?=$this->baseUrl('/js/jquery/jquery-ui.js')?>" ></script>
    <script src="<?=$this->baseUrl('/js/ready.js')?>" ></script>
    <script src="<?=$this->baseUrl('/js/messages.js')?>" ></script>
    <!--[if lt IE 9]>
    <script src="<?=$this->baseUrl('/js/html5.js')?>"></script>
    <![endif]-->
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <base href="<?php echo $this->baseUrl() ?>"/>
</head>