<?php

$this->headLink(array(
    'rel' => 'favicon',
    'href' => $this->baseUrl('/favicon.ico'),
    'type' => 'image/x-icon'
));

$this->asset('dashboard');

?>
<head>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headTitle($this->__('Admin Panel'))->setSeparator(': ') ?>
    <?php echo $this->headLink()->prependStylesheet('http://maksslesarenko.github.com/google-plus-ui/css/jquery-ui-1.8.16.google.plus.css') ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <base href="<?php echo $this->baseUrl() ?>"/>
</head>