<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="i-bar"></span>
                <span class="i-bar"></span>
                <span class="i-bar"></span>
            </a>
            <a class="brand" href="/">ZFCore</a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li>
                        <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index')) ?>"
                               title="Dashboard">Dashboard</a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url(array('module' => 'index', 'controller' => 'index', 'action' => 'index')) ?>"
                               title="View the Site">View the Site</a>
                    </li>
                </ul>
                <? if (false) : ?>
                    <p class="navbar-text pull-right">
                        <?php /*echo $this->__('Logged in as %s', ($this->url('users', 'profile') ?'': $identity->login))*/?>
                        (<?=$this->url(array('module'=>'users', 'controller'=> 'login', 'action' => 'logout'))?>)
                    </p>
                <? else: ?>
                <ul class="nav pull-right">
                    <li><a href="<?=$this->url(array('module'=>'users', 'controller'=>'login', 'action' => 'index'))?>">Login</a></li>
                </ul>
                <? endif; ?>
                <div id="loading"></div>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>

