<noscript><!-- Show a notification if the user has disabled javascript -->
    <div class="notification error">
        <div>
            <?php $this->_e('Javascript is disabled or is not supported by your browser.' .
                            'Please <a href="http://browsehappy.com/" title="Upgrade to a better browser">upgrade</a> your browser or ' .
                            '<a href="http://www.google.com/support/bin/answer.py?answer=23852" title="Enable Javascript in your browser">enable</a>' .
                            'Javascript to navigate the interface properly.') ?>
        </div>
    </div>
</noscript>

<?php if ($this->FlashMessenger()->count() || $this->messages): ?>
<div id="messages" class="opacity shadow" style="display:none">
    <ul>
        <?php foreach ($this->FlashMessenger()->getMessages() as $message): ?>
            <li><?php echo $this->__($message) ?></li>
        <?php endforeach; ?>

        <?php foreach ((array)$this->messages as $message): ?>
            <li><?php echo $this->__($message) ?></li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>