<?php
$this->enableDojo = true;

$this->dojo()->addStyleSheet($this->dojo()->getCdnBase() . $this->dojo()->getCdnVersion() . '/dojox/grid/resources/tundraGrid.css')
             ->requireModule('core.grid.logs.Logs')
             ->onLoadCaptureStart();
?>
function(){
    var cells = [
    {
        name: "<?php $this->_e('Id')?>",
        field: "id",
        width:'100px',
        hidden: "true"
    },
    {
        name: "<?php $this->_e('Name')?>",
        field: "name",
        width:'auto'
    },
    {
        name: "<?php $this->_e('Path')?>",
        field: "path",
        width:'auto'
    },
    {
        name: "<?php $this->_e('Size')?>",
        field: "size",
        width:'auto'
    },
    ];

    dojo.require('core.grid.logs.Logs');
    var datagrid = new core.grid.logs.Logs(cells,
                                           'gridContainer',
                                         '<?php echo $this->url();?>',
                                         true,
                                         true);
}
<?php $this->dojo()->onLoadCaptureEnd(); ?>

<div class="gridControl">
<?php
    echo $this->comboBox('grid-field',
                         'id',
                         array('jsid'=>'grid-field','autocomplete' => false),
                         array(),
                         array('name'   => $this->__('Name'),
                               'path'   => $this->__('Path'),
                               'size'   => $this->__('Size'),
                              )
                        );
    echo $this->validationTextBox('grid-filter',
                                  '*',
                                  array('jsid'=>'grid-filter',
                                        'regExp'=> '[\S\s]+',
                                        'required'=> 'true'),
                                  array('style'=>'padding:2px 1px 1px')
                                  );

    echo $this->button('grid-search',
                       $this->__('Filter'),
                       array('jsid'      => 'grid-search',
                             'baseClass' => 'gridButton'));
    echo $this->button('grid-undo',
                       $this->__('Undo'),
                       array('jsid'      => 'grid-undo',
                             'baseClass' => 'gridButton'));
?>
</div>


<div class="gridContainer" id="gridContainer" style="height:600px;"></div>


