<?php
$this->enableDojo = true;

$this->headLink()->appendStylesheet($this->baseUrl('http://ajax.googleapis.com/ajax/libs/dojo/1.5/dijit/themes/claro/claro.css'));
$this->headScript()->appendScript(
    "dojo.setObject('page.LogReader.addNumber', $this->addNumber); " .
    "dojo.setObject('page.LogReader.logId', '$this->id'); " .
    "dojo.setObject('page.LogReader.beginLogString', '$this->beginLogString'); "
);
$this->javascript()->controller();
$this->stylesheet()->controller();
?>

<h2><?php echo $this->name?></h2>

<input type="button" value="<?php echo $this->addLabelBegin?>" id="addButtonBegin">
<br/>

<div id="contentBegin">
</div>

<div id="content">
    <?php foreach ($this->logs as $key =>$log):?>
        <div class="log-lines" id="<?php echo $key ?>">
            <?php echo $log ?>
        </div>
    <?php endforeach ?>
</div>

<div id="contentEnd">
</div>

<br/>
<input type="button" value="<?php echo $this->addLabelEnd?>" id="addButtonEnd">



