<h1>Login</h1>
<h3>Use <strong>admin:123456</strong> for login</h3>
<hr/>
<article>
<?php echo $this->form; ?>

<p class="small">
    <a href="<?php echo $this->url(array('module' => 'users',
                                         'controller'=>'register',
                                         'action'=>'index'),
                                   'default'); ?>"><?php echo $this->__('Register now')?></a> |
    <a href="<?php echo $this->url(array('module' => 'users',
                                         'controller'=>'register',
                                         'action'=>'forget-password'),
                                   'forgetPassword'); ?>"><?php echo $this->__('Forget Password')?></a>

    <?php if ($this->google):?>        |
        <a href="<?php echo $this->url(array('module' => 'users', 'controller' => 'auth', 'action' => 'index', 'provider' => 'google'), 'userAuth');?>">
            <?php echo $this->__('Sign in with Google')?>
        </a>
    <?php endif;?>

    <?php if ($this->twitter):?>        |
        <a href="<?php echo $this->url(array('module' => 'users', 'controller' => 'auth', 'action' => 'index', 'provider' => 'twitter'), 'userAuth');?>">
            <?php echo $this->__('Sign in with Twitter')?>
        </a>
    <?php endif;?>

    <?php if ($this->facebook):?>        |
        <a href="<?php echo $this->url(array('module' => 'users', 'controller' => 'auth', 'action' => 'index', 'provider' => 'facebook'), 'userAuth');?>">
            <?php echo $this->__('Sign in with Facebook')?>
        </a>
    <?php endif;?>
</p>
</article>
