<h1>Login</h1>
<h3>Use <strong>admin:123456</strong> for login</h3>
<div>
<?php echo $this->form; ?>
<p class="small">
    <a href="<?php echo $this->url(array('module' => 'users',
                                         'controller'=>'register',
                                         'action'=>'index'),
                                   'default'); ?>">Register now</a> |
    <a href="/forget-password">Forget Password</a>
</p>
</div>

