                    <h2><?php echo $this->__('Enter new password');?></h2>
                            <form action=""
								  name="<?php echo $this->form->getName(); ?>"
								  id="<?php echo $this->form->getId(); ?>"
								  enctype="<?php echo $this->form->getEnctype(); ?>"
								  method="<?php echo $this->form->getMethod();?>">


                        <div class="clearfix">
                            <label for="passw"><?php echo $this->__('Password');?><sup>*</sup></label>
                            <div class="input">
                            	<?php echo $this->form->passw; ?>
                            </div>
                        </div>
                        <div class="clearfix">
                            <label for="passw_again"><?php echo $this->__('Password again');?><sup>*</sup></label>
                            <div class="input">
                            	<?php echo $this->form->passw_again; ?>
                            </div>
                        </div>
                        <div class="clearfix">
	                        <div class="input">
	                        <?php echo $this->form->change; ?>
	                        </div>
                        </div>
                    </form>