<?php if ($this->rowset ->count()): ?>
    <div id="comments">
        <?php foreach($this->rowset as $row): ?>
            <ul class="commentlist">
                <li id="li-comment-1" class="comment">
                    <img src="<?php echo $this->avatar($row->avatar, $row->email)?>"
                         alt="<?php echo $this->__('Avatar for')?> <?php echo $row->login?>"
                         title="<?php echo $this->__('Avatar for')?> <?php echo $row->login?>"
                         class="avatar"/>
                    <article class="comment" id="comment-1">
                        <?php echo ucfirst($row->login)?> <?php echo $this->__('on')?> <?php echo $this->date($row->created)?> <?php echo $this->__('said')?>:
                        <span class="says">said:</span>

                        <p><?php echo $row->body ?></p>
                    </article>
                </li>
            </ul>
        <?php endforeach;?>
    </div>
<?php endif;?>

<?php $user = $this->user();?>

<?php if ($user):?>
    <ul class="commentlist">
        <li id="li-comment-1" class="comment">

            <img src="<?php echo $this->avatar($user)?>" title="<?php echo $this->__('Avatar for')?> <?php echo $user->login?>" class="avatar"/>

            <?php echo $this->form;?>
        </li>
    </ul>
<?php endif?>
