<?php if (count($this->comments)>0): ?>
    <div id="comments">
        <?php foreach($this->comments as $comment): ?>
            <ol class="commentlist">
                <li id="li-comment-1" class="comment even thread-even depth-1">
                    <article class="comment" id="comment-1">
                        <?php echo ucfirst($comment->login)?> <?php echo $this->__('on')?> <?php echo $this->date($comment->created)?> <?php echo $this->__('said')?>:
                        <span class="says">said:</span>

                        <p><?php echo $comment->body ?></p>
                    </article>
                </li>
            </ol>
        <?php endforeach;?>
    </div>
<?php endif;?>

<?php echo $this->form;?>
