<?php $this->headScript()->captureStart();?>
    IMAGES_URL = '<?php echo $this->url(array('action'=> 'index', 'controller' => 'images'));?>';
<?php $this->headScript()->captureEnd();

    $this->stylesheet()->controller();
    
    $this->dojo()
         ->requireModule('dijit.form.Button')
         ->requireModule('dojox.layout.FloatingPane') 
         ->requireModule('dojox.editor.plugins.Preview') 
         ->requireModule('dijit._editor.plugins.FullScreen') 
         ->requireModule('dijit._editor.plugins.ViewSource') 
         ->requireModule('core.editor.plugins.ImageManager')
         ;
         
    echo $this->editForm;
?>