<div class="header">
    <div class="cont_width">
        <div class="logo">
            <h1><a href="/" title="Homepage">Core</a></h1>
            <h2>Content Management Framework</h2>
        </div>
    </div>
    <div class="topgreen clear">
        <div class="cont_width">
        </div>
    </div>
    <div class="tophelp">
        <div class="cont_width">
            <?php echo $this->__('ZFCore Installer')?>
        </div>
    </div>
</div>