<div class="header">
    <div class="cont_width">
        <div class="logo">
            <h1><a href="/" title="Homepage">Core</a></h1>
            <h2>Content Management Framework</h2>
        </div>
    </div>
    <div class="topgreen clear">
        <div class="cont_width">
        </div>
    </div>
    <div class="tophelp">
        <div class="cont_width">


            <ul>
                <li class="left"><?php echo $this->__('ZFCore Installer');?></li>

                <?php if (in_array(false, $this->progress)):?>
                    <?php foreach ($this->progress as $route => $status):?>
                        <li class="left"><?php if (false !== $status && isset($this->pages[$route])):?><span class="pageDelimiter"></span><a href="<?php echo $this->url(array(), $route)?>"><?php echo $this->pages[$route]?></a>
                            <?php endif?>
                        </li>
                    <?php endforeach;?>
                <?php else:?>
                    <li class="left">&nbsp; » &nbsp; <?php echo $this->__('Installation Complete');?></li>
                <?php endif?>
            </ul>
        </div>
    </div>
</div>