<h1>
    <?php echo $this->row->title?>
    <?php if ($this->row->isOwner()) : ?>
        <a href="<?php echo $this->url(array(
                                'module' => 'blog',
                                'controller' => 'post',
                                'action' => 'edit',
                                'alias'  => $this->row->alias), 'default', true) ?>" title="<?php $this->_e('Edit Post')?>" class="btn pull-right"><?php $this->_e('Edit Post')?></a>
    <?php endif; ?>
</h1>
<hr />
<article>
    <div class="content">
        <?php echo $this->row->body?>
    </div>
    <footer>
        <?php echo $this->__('Posted on')?> <?php echo $this->date($this->row->published)?>
        <?php echo $this->__('by')?>
        <a href="<?php echo $this->url(array('login' => $this->user->login), 'blogauthor') ?>"><?php echo $this->user->login?></a>
        <?php echo $this->__('in')?>
        <a href="<?php echo $this->url(array('alias' => $this->category->alias), 'blogcategory') ?>"><?php echo $this->category->title?></a>
    </footer>
</article>
<?php echo $this->getComments('blog',
    array(
        'key' => $this->row->id,
        'template' => 'blog'
    )
) ?>