<?php
    $this->headScript()->prependFile($this->baseUrl('scripts/tiny_mce/tiny_mce.js'));
    $this->stylesheet()->module();
?>
<article>
    <header>
        <h3><?php echo $this->row->title?></h3>
        <div><?php echo $this->__('Posted on')?> <?php echo $this->date($this->row->published)?></div>
    </header>
  <div>
    <?php echo $this->row->body?>
  </div>
  <footer>
      <?php echo $this->__('Posted by')?>
      <a href="<?php echo $this->url(array('login' => $this->user->login), 'blogauthor') ?>"><?php echo $this->user->login?></a>
      <?php echo $this->__('in')?>
      <a href="<?php echo $this->url(array('alias' => $this->category->alias), 'blogcategory') ?>"><?php echo $this->category->title?></a>
  </footer>
</article>

<?php echo $this->action('index', 'comment', 'blog', array('postId' => $this->row->id));?>