<?php $user = $this->user();?>
<ul class="commentlist">
    <li class="comment">
        <?php if ($user->avatar):?>
            <img src="<?php echo $this->baseUrl($user->avatar)?>" title="<?php echo $this->__('Avatar for')?> <?php echo $user->login?>" class="avatar"/>
        <?php else:?>
            <?php echo $this->gravatar($user->email, array(), array('title' => $this->__('Avatar for') . ' '  . $user->getName(), 'class' => 'avatar'))?>
        <?php endif;?>
        <?php echo $this->form;?>

    </li>
</ul>