<h3>
	<a href="<?php echo $this->url(array('alias'=> $this->category->alias), 'forumcategory') ?>"><?php echo $this->category->title; ?></a>
	[<a href="<?php echo $this->url(array('alias'=> $this->category->alias), 'forumcategoryrss') ?>"><?php echo $this->__('rss'); ?></a>]
</h3>
<ul class="commentlist">
    <li class="comment">
        <img src="<?php echo $this->avatar($this->author->avatar, $this->author->email)?>"
             alt="<?php echo $this->__('Avatar for')?> <?php echo $this->author->login?>"
             title="<?php echo $this->__('Avatar for')?> <?php echo $this->author->login?>"
             class="avatar"/>
        <article>
            <header>
                <div class="right">#<a href="#comment-1">1</a></div>
                <h4>
                    <?php echo $this->post->title; ?>
                    [<a href="<?php echo $this->url(array('id'=> $this->post->id), 'forumpostrss') ?>"><?php echo $this->__('rss'); ?></a>]
                </h4>
                <?php echo $this->author->login; ?>
                <?php echo $this->__('at')?>
                <?php echo $this->date($this->post->created); ?>

            </header>
            <br />
            <div style="position:relative;"><?php echo $this->post->body; ?></div>
        </article>
    </li>
</ul>

<?php echo $this->getComments('forum-post', 
    array(
        'key' => $this->post->id,
        'template' => 'forum'
    )
) ?>
