<?php
    $this->stylesheet()->module();
?>
<h3>
	<a href="<?php echo $this->url(array('alias'=> $this->category->alias), 'forumcategory') ?>"><?php echo $this->category->title; ?></a>
	[<a href="<?php echo $this->url(array('alias'=> $this->category->alias), 'forumcategoryrss') ?>"><?php echo $this->__('rss'); ?></a>]
</h3>
<article class="comment">
    <header>
        <h4>
            <?php echo $this->post->title; ?>
            [<a href="<?php echo $this->url(array('id'=> $this->post->id), 'forumpostrss') ?>"><?php echo $this->__('rss'); ?></a>]
        </h4>
        <?php echo $this->author->login; ?>
        <?php echo $this->__('at')?>
        <?php echo $this->date($this->post->created); ?>
    </header>
    <br />
    <div style="position:relative;"><?php echo $this->post->body; ?></div>
</article>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>

<?php foreach($this->paginator as $i => $row): ?>
	<br />
    <article id="comment-<?php echo ++$i?>" class="comment">
       <header>
           <h5><?php echo $row->title; ?></h5>
           <?php echo $this->author->login; ?>
           <?php echo $this->__('at')?>
           <?php echo $this->date($row->created); ?>
           <div class="right">#<a href="#comment-<?php echo $i?>"><?php echo $i?></a></div>
       </header>
       <br />
       <div style="position:relative;"><?php echo $row->body; ?></div>
    </article>

<?php endforeach;?>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>

<?php echo $this->action('comment', 'post', 'forum', array('postId' => $this->post->id));?>