<?php

$this->headTitle($this->page->title, Zend_View_Helper_Placeholder_Container_Abstract::PREPEND)->setSeparator(' » ');
$this->headMeta()->appendName('keywords', empty($this->page->keywords) ? $this->page->title : $this->page->keywords);
$this->headMeta()->appendName('description', empty($this->page->description) ? $this->page->title : $this->page->description);

echo $this->page->content;
