<div class="span3">
<h4><a href="<?php echo $this->url(array('module'=>'users', 'controller'=>'management'))?>"><i class="icon-user"></i> Users</a></h4>

<table class="table table-condensed well">
  <tbody>
    <tr>
      <th>Total Users</th>
      <td width="50px"><?php echo $this->totalUsers ?></td>
    </tr>
    <tr>
      <th>Active Users</th>
      <td><?php echo $this->activeUsers ?></td>
    </tr>
  </tbody>
</table>
</div>
