<?php 
    $this->stylesheet()->module();
    $this->javascript()->module();
    $jsTranslate = array(
        'hide' => $this->__('hide'),
        'show' => $this->__('show'),
    );
    $this->headScript()->appendScript('var translate = ' . json_encode($jsTranslate) . ';');
?>
<div class="faq-contents">
    <div>
        <?php $this->_e('Contents'); ?>
        <a href="#" id="faq-content">[<?php $this->_e('hide'); ?>]</a>
    </div>
    <div id="faq-content-question">
    <?php    
        foreach($this->question as $i => $question){
            echo '<a href="#faq-' . $i . '">' . $question->question . '</a><br>';
        }
    ?>
    </div>
</div>
<div class="faq-questions">
    <?php    
        foreach($this->question as $i => $question){
            echo '<div id="faq-' . $i . '" class="faq-question">' . $question->question . '</div>';
            echo '<div class="faq-answer">' . $question->answer . '</div>';
        }
    ?>
</div>