<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <body class="tundra">
        <?php echo $this->render('dashboard/partial/head.phtml') ?>
        <!-- Wrapper for the radial gradient background -->
        <div id="body-wrapper">
            <!-- Main Content Section with everything -->
            <div id="main-content">
                <?php echo $this->render('dashboard/partial/messages.phtml') ?>

                <div class="content shadow"><?php echo $this->layout()->content ?></div>
                <div class="clear"></div>

                <?php echo $this->render('dashboard/partial/footer.phtml') ?>
            </div>
            <!-- End #main-content -->
        </div>
    </body>
</html>