<!DOCTYPE html>
<html dir="ltr" lang="en-US">
    <?php echo $this->render('dashboard/partial/head.phtml') ?>
    <body>
    <?php echo $this->render('dashboard/partial/messages.phtml') ?>
    <div class="container">
        <div class="row">
            <div class="span4 offset4">
                <?php echo $this->layout()->content ?>
            </div>
        </div>
        <hr />
        <footer>
            <p align="center">&copy; <?=gmdate('Y')?> NIX Solutions Ltd</p>
        </footer>
    </div>
    </body>
</html>
