<?php echo $this->render('dashboard/partial/header.phtml');?>

    <div id="body-wrapper"> <!-- Wrapper for the radial gradient background -->
    
        <?php echo $this->render('dashboard/partial/navigation.phtml');?>

        <div id="main-content"> <!-- Main Content Section with everything -->

            <?php echo $this->render('dashboard/partial/messages.phtml');?>
            
            <?php if ($this->navigation()->breadcrumbs()->render()): ?>
                <div class="breadcrumbs shadow"><?php echo $this->navigation()->breadcrumbs()->setSeparator(' &raquo; '); ?></div>    
            <?php endif; ?>
            
            <div class="content shadow">
                <?php echo $this->layout()->content ?>
            </div>
            
            <div class="clear"></div>

            <div id="footer">
                <small>
                    &#169; Copyright 2010 <a href="http://nixsolutions.com" title="NIX Solutions Ltd.">NIX Solutions Ltd.</a>
                </small>
            </div><!-- End #footer -->

        </div> <!-- End #main-content -->

<?php echo $this->render('dashboard/partial/footer.phtml');?>