<?php

$request = Zend_Controller_Front::getInstance()->getRequest();
$class = array();
$class[] = 'm-' . $request->getModuleName();
$class[] = 'c-' . $request->getControllerName();
$class[] = 'a-' . $request->getActionName();

?>
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <body class="<?php echo implode(' ', $class) ?>">
        <?php echo $this->render('dashboard/partial/head.phtml') ?>
        <!-- Wrapper for the radial gradient background -->
        <div id="body-wrapper">
            <?php echo $this->render('dashboard/partial/navigation.phtml') ?>
            <!-- Main Content Section with everything -->
            <div id="main-content">
                <?php echo $this->render('dashboard/partial/messages.phtml') ?>

                <?php if ($this->navigation()->breadcrumbs()->render()): ?>
                    <div class="breadcrumbs shadow"><?php echo $this->navigation()->breadcrumbs()->setSeparator(' &raquo; ') ?></div>
                <?php endif; ?>

                <div class="content shadow"><?php echo $this->layout()->content ?></div>
                <div class="clear"></div>

                <?php echo $this->render('dashboard/partial/footer.phtml') ?>
            </div>
            <!-- End #main-content -->
        </div>
    </body>
</html>