<?php 
    $this->stylesheet()->module(); 
    $this->stylesheet()->action();
?>

<div style="width:70%; float:left;">
  <p>Last Posts:</p>
  
  <div class="blog-post">
  <?php if (count($this->paginator)>0): ?>
  <?php foreach($this->paginator as $post): ?>
    <h2><a href="<?php echo $this->url(array('controller'=>'post', 'action'=>'index', 'id'=>$post['id'])) ?>"><?php echo $post['post_title'] ?></a></h2>
    <hr />
    <pre style="font-size:1.5em;"><?php echo $post['post_text'] ?></pre>
    <br />
    author: <?php echo $post['login'] ?></td>
    <?php //echo $post['post_view_count'] ?>
    <?php //echo $post['count_comments'] ?>
  <?php endforeach; ?>
  <?php endif; ?>
  </div>
  <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
</div>

<div style="width:30%; float:left;">
  <p>Categories:</p>
  <div class="tree-categories"><?php echo $this->cats; ?></div>
</div>

<div class="clear" />