<?php if ($this->pageCount > 1): ?>
    <div id="pagination">
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&lt; <?php echo $this->__('Back');?></a>
        <?php else: ?>
            <span class="disabled">&lt; <?php echo $this->__('Back');?></span>
        <?php endif; ?>

        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a>
            <?php else: ?>
                <?php echo $page; ?>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if (isset($this->next)):?>
            <a href="<?php echo $this->url(array('page' => $this->next)); ?>"><?php echo $this->__('Next');?> &gt;</a>
        <?php else:?>
            <span class="disabled"><?php echo $this->__('Next');?> &gt;</span>
        <?php endif;?>
    </div>
<?php endif;?>