<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
          <?php 
          
                echo $this->headMeta() ;
                echo $this->headTitle($this->__('Image Manager'));
           
                echo $this->dojo()
                          ->enable()
                          ->setCdnBase(Zend_Dojo::CDN_BASE_GOOGLE)
                          ->setCdnDojoPath(Zend_Dojo::CDN_DOJO_PATH_GOOGLE)
                          ->setCdnVersion('1.5.0')
                          ->registerModulePath('core', '/scripts/core')
                          ->setDjConfig(array('isDebug' => false, 'parseOnLoad' => true, 'baseUrl' => './'))
                          ->addStyleSheetModule('dijit.themes.tundra')
                          ->addStyleSheet($this->dojo()->getCdnBase() . $this->dojo()->getCdnVersion() . '/dojox/form/resources/FileInput.css')
                          ->requireModule('dojo.parser')
                          ->requireModule('dijit.form.Button')
                          ->requireModule('dijit.form.TextBox')
                          ->requireModule('dijit.form.ComboBox')
                          ->requireModule('dijit.form.RadioButton')
                          ->requireModule('dijit.form.CheckBox')
                          ->requireModule('dijit.form.Textarea')
                          ->requireModule('dojox.layout.FloatingPane')
                          ->requireModule('dijit.Toolbar')
                          ->requireModule('dojox.form.FileInput')
                          //->addOnLoad('onLoad')
                          ;
                          
                $this->stylesheet()->controller();
                $this->javascript()->controller();
                
                echo $this->headLink();
                echo $this->headScript();
        ?>
        <script type="text/javascript">
        //<![CDATA[
            var DELETE_URL      = '<?php echo $this->url(array("action"=> "delete"));?>';
            var THUMB_URL       = '<?php echo $this->url(array("action"=> "thumb"));?>';
            var THUMB_DIR       = '<?php echo $this->aOptions["thumbDir"];?>';
            var ERROR_THUMB_CREATION = '<?php echo $this->aOptions["errors"]["thumb"];?>';
            var RESULT_SUCCESS  = '<?php echo $this->sSuccess?>';
            var VALID_FILES     = ['<?php echo join("', '", $this->aOptions["extensions"]);?>'];
            var ERROR_FILE_TYPE = '<?php echo $this->aOptions["errors"]["filetype"];?>';
        //]]>            
        </script>
    </head>
    <body class="tundra">