<h3>ZFCore CMF System</h3>
<hr/>
<div>
    <p>
        ZFCore is a content management framework based on Zend Framework. It was developed by PHP Team of 
        <a href="http://nixsolutions.com/">NIX Solutions Ltd</a>. In case you are interested in getting a multifunctional,
        secure project reliable in data processing like ZFCore, you can always turn to our skillful and experienced team
        of PHP developers. Moreover, we don't limit ourselves with PHP because sometimes it's useful to support projects
        with mobile applications. iPhone and Android Teams of NIX Solutions Ltd. are always ready to help and develop
        for you any kind of mobile apps.
    </p>
    <p>Used libraries:</p>
    <ul>
        <li><a href="http://framework.zend.com/">Zend Framework 1.xx (latest)</a> &mdash;
            <a href="http://framework.zend.com/license">New BSD License</a></li>
        <li><a href="http://jquery.com">jQuery</a> &mdash;
            <a href="http://jquery.org/license/">Dual licensed under the MIT or GPL Version 2 licenses</a></li>
        <li><a href="http://jqueryui.com/">jQuery UI</a> &mdash;
            <a href="http://jquery.org/license/">Dual licensed under the MIT or GPL Version 2 licenses</a</li>
        <li><a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a> &mdash;
            <a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License v2.0</a></li>
        <li><a href="http://imperavi.com/redactor/">Imperavi jQuery redactor</a> &mdash;
            you may use Redactor for non-commercial websites for free,
            redactor has three different licenses available for commercial use.
            For further details please see the
            <a href="http://redactorjs.com/license/">License Agreement</a></li>
        <li>Icons Graciously provided by <a href="http://glyphicons.com/">Glyphicons</a> &mdash;
            <a href="http://creativecommons.org/licenses/by/3.0/">CC BY 3.0</a></li>
    </ul>
    <p>
        Any questions, wishes, or offers? Feel free to contact us by <a href="mailto:ask@nixsolutions.com">ask@nixsolutions.com</a>
    </p>
</div>
