<h3>ZFCore CMF System</h3>
<hr/>
<div>
    <p>ZFCore &mdash; content management framework based on Zend Framework. It developed by PHP Team of <a href="http://nixsolutions.com/">NIX Solutions Ltd.</a></p>
    <p>Using libraries:</p>
    <ul>
        <li><a href="http://framework.zend.com/">Zend Framework 1.xx (latest)</a></li>
        <li><a href="http://jquery.com">jQuery</a></li>
        <li><a href="http://jqueryui.com/">jQuery UI</a></li>
        <li><a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a></li>
        <li><a href="http://addyosmani.github.com/jquery-ui-bootstrap/">Bootstrap jQuery UI</a></li>
        <li>Icons Graciously provided by <a href="http://glyphicons.com/">Glyphicons</a></li>
    </ul>

</div>
