<?php
$this->enableDojo = true;

$this->dojo()->addStyleSheet($this->dojo()->getCdnBase() . $this->dojo()->getCdnVersion() . '/dojox/grid/resources/tundraGrid.css')
             ->requireModule('core.grid.crontab.Crontab')
             ->onLoadCaptureStart();
?>
function(){
    var cells = [
    {
        name: "<?php $this->_e('Id')?>",
        field: "id",
        width:'100px',
        hidden: "true"
    },
    {
        name: "<?php $this->_e('Minute')?>",
        field: "minute",
        width:'auto'
    },
    {
        name: "<?php $this->_e('Hour')?>",
        field: "hour",
        width:'auto'
    },
    {
        name: "<?php $this->_e('Day of Month')?>",
        field: "dayOfMonth",
        width:'auto'
    },
    {
        name: "<?php $this->_e('Month')?>",
        field: "month",
        width:'auto'
    },
    {
        name: "<?php $this->_e('Day of Week')?>",
        field: "dayOfWeek",
        width:'auto'
    },
    {
        name: "<?php $this->_e('Command')?>",
        field: "command",
        width:'auto'
    },
    ];

    dojo.require('core.grid.crontab.Crontab');
    var datagrid = new core.grid.crontab.Crontab(cells,
                                           'gridContainer',
                                         '<?php echo $this->url();?>',
                                         true,
                                         true);
}
<?php $this->dojo()->onLoadCaptureEnd(); ?>

<div class="gridControl">
<?php
    echo $this->comboBox('grid-field',
                         'id',
                         array('jsid'=>'grid-field','autocomplete' => false),
                         array(),
                         array('minute'  => $this->__('Minute'),
                               'hour'   => $this->__('Hour'),
                               'dayOfMonth'   => $this->__('Day Of Month'),
                               'month'   => $this->__('Month'),
                               'dayOfWeek'   => $this->__('Day Of Week'),
                               'command'   => $this->__('Command'),
                              )
                        );
    echo $this->validationTextBox('grid-filter',
                                  '*',
                                  array('jsid'=>'grid-filter',
                                        'regExp'=> '[\S\s]+',
                                        'required'=> 'true'),
                                  array('style'=>'padding:2px 1px 1px')
                                  );

    echo $this->button('grid-search',
                       $this->__('Filter'),
                       array('jsid'      => 'grid-search',
                             'baseClass' => 'gridButton'));
    echo $this->button('grid-undo',
                       $this->__('Undo'),
                       array('jsid'      => 'grid-undo',
                             'baseClass' => 'gridButton'));
?>
</div>

<div class="gridContainer" id="gridContainer" style="height:300px;"></div>

<div class="gridControl">
<?php
    echo $this->button('grid-new',
                       $this->__('Create New'),
                       array('jsid'      => 'grid-new',
                             'baseClass' => 'gridButton'));
    echo $this->button('grid-del',
                       $this->__('Delete Selected'),
                       array('jsid'      => 'grid-del',
                             'baseClass' => 'gridButton'));
?>
</div>
