<?php echo '<?xml version="1.0" encoding="utf-8"?>'; ?>
<response result="success">
    <?php foreach($this->data as $table => $data): ?>
    <?php if (sizeof($data) == 0) continue; ?>
    <table name="<?php echo $table; ?>">
        <?php foreach($data as $item): ?>
        <?php if (sizeof($item) == 0) continue; ?>
        <item>
            <?php foreach($item as $key => $value): ?>
            <<?php echo $key; ?>><?php echo $value; ?></<?php echo $key; ?>>
            <?php endforeach; ?>
        </item>
        <?php endforeach; ?>
    </table>
    <?php endforeach; ?>
</response>