<?php

$request = Zend_Controller_Front::getInstance()->getRequest();
$class = array();
$class[] = $request->getModuleName();
$class[] = $request->getControllerName();
$class[] = $request->getActionName();

?>
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<?php echo $this->render('default/partial/head.phtml') ?>
<body class="<?php echo implode('-', $class) ?>">
    <?php echo $this->render('default/partial/messages.phtml') ?>
    <div class="body">
        <?php echo $this->render('default/partial/header.phtml') ?>
        <div class="content cont_width"><?php echo $this->layout()->content ?></div>
        <div class="clear">&nbsp;</div>
        <?php echo $this->render('default/partial/footer.phtml') ?>
    </div>
</body>
</html>