<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headTitle() ?>
    <base href="<?php echo $this->baseUrl();?>" />
    <?php $this->headLink()
               ->prependStylesheet($this->baseUrl('layouts/default/css/style.css'))
               ->headLink(array('rel' => 'shortcut icon', 'href' => $this->baseUrl('/favicon.ico'), 'type' => 'image/x-icon'), 'PREPEND')?>
    <?php $this->headScript()->prependFile($this->baseUrl('scripts/jquery/jquery.js?ver=1.4.2'));?>
    <?php $this->headScript()->appendFile($this->baseUrl('layouts/default/scripts/ui.js'));?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headScript(); ?>
</head>
<body>
    <?php if (0 != $this->FlashMessenger()->count() or $this->messages) :?>
        <div id="messages" class="opacity shadow" style="display: none;">
            <ul>
            <?php
                foreach ($this->FlashMessenger()->getMessages() as $message) :
                      echo "<li>".$this->__($message)."</li>";
                endforeach;
            ?>
            <?php
                foreach ((array)$this->messages as $message) :
                      echo "<li>".$this->__($message)."</li>";
                endforeach;
            ?>
            </ul>
        </div>
    <?php endif; ?>
    <div class="body">
        <div class="header">
            <div class="cont_width">
                <div class="logo">
                    <h1><a href="/" title="Homepage">Core</a></h1>
                    <h2>Content Management Framework</h2>
                </div>
                <div class="menu small">
                    <?php //echo $this->navigation()->menu()->setMinDepth(0)->setMaxDepth(0); ?>

                </div>
                <div class="menu clearright">
                <?php echo $this->getMenu(13)->setMinDepth(0)->setMaxDepth(1); ?>
                    <?php //echo $this->navigation()->menu()->setMinDepth(1)->setMaxDepth(1); ?>
                    <br class="clear"/>
               <?php

          // echo $this->getMenu(13)->setMinDepth(0)->setMaxDepth(0); ?>
                       <?php //echo $this->getMenu(12)->setMinDepth(1)->setMaxDepth(1); ?>
                </div>
            </div>
            <div class="topgreen clear">
                <div class="cont_width">
                <?php
                    $titleArr = $this->headTitle()->getIterator();
                    $title = reset($titleArr);
                    if (sizeof($titleArr) != 1) {
                        echo $title;
                    } else {
                        $nav = $this->navigation()->menu()->setMinDepth(1)->setMaxDepth(1)->findByActive('true');
                        if ($nav) {
                        //showing page title or smthn another from navigation
                        //done only for 1st lev navigation
                            echo $nav->getLabel();
                        } else {
                            echo '&nbsp;';
                        }
                    }
                    ?>
                </div>
            </div>
            <div class="tophelp">
                <div class="cont_width">
	                <div class="simpleMenu">
	                <?php //echo $this->navigation()->menu($this->getMenu()->byMark('usermenu'))->setPartial('default/partial/breadcrumbs.phtml'); ?>
	                    <br class="clear"/>
	                </div>
                    Here goes help text
                </div>
            </div>
        </div>
        <!--<?php //echo $this->navigation()->getMenu('usermenu'); ?>-->



        <?php //echo $this->navigation($this->getMenu('usermenu'))->menu()->findOneByLabel('Registration'); ?>
              <?php //echo $this->navigation($this->getMenu('adminmenu'))->menu(); ?>

        <div class="content cont_width">
            <?php echo $this->layout()->content ?>
        </div>

        <div class="footer">
            <div class="cont_width">
                <div class="footer_logo">
                    &nbsp;
                </div>
                <div>
                    <ul>
                        <li>
                            <h4>Home </h4>
                        </li>
                        <li>
                            <?php echo ($this->navigation()->menu()->setMinDepth(1)->setMaxDepth(1)); ?>
                        </li>
                    </ul>
                    <ul>
                        <li><h4>Terms of use</h4></li>
                        <li>Privacy policy</li>
                        <li>Terms and conditions</li>
                    </ul>
                </div>
                <div class="clear">
                    &#169; Copyright <?php echo date('Y') ?> <a href="http://nixsolutions.com" title="NIX Solutions Ltd.">NIX Solutions Ltd.</a>
                </div>
            </div>
        </div>
    </div>
</body>
</html>