<?php

$request = Zend_Controller_Front::getInstance()->getRequest();
$class = array();
$class[] = 'm-' . $request->getModuleName();
$class[] = 'c-' . $request->getControllerName();
$class[] = 'a-' . $request->getActionName();

?>
<!DOCTYPE html>
<html dir="ltr" lang="en-US">
    <?php echo $this->render('default/partial/head.phtml') ?>
    <body class="<?php echo implode(' ', $class) ?>" data-spy="scroll" data-target=".subnav" data-offset="50">
    <?php echo $this->render('default/partial/messages.phtml') ?>
    <?php echo $this->render('default/partial/menu.phtml') ?>
    <div class="container well">
        <div class="row-fluid">
            <div class="content">
                <?php echo $this->layout()->content ?>
            </div>
        </div>
    </div>
    <hr />
    <footer class="container">
        <p align="center">&copy; <?=gmdate('Y')?> NIX Solutions Ltd</p>
    </footer>
    </body>
</html>