<?php $this->plugins()->fancybox(); ?>

<?php if ($this->rowset->count()): ?>
    <div id="comments">
        <?php foreach($this->rowset as $row): ?>
            <ul class="commentlist">
                <li id="li-comment-<?php echo $row->id ?>" class="comment">
                    
                    <?php if ($row->avatar):?>
                        <img src="<?php echo $this->baseUrl($row->avatar)?>"
                             alt="<?php echo $this->__('Avatar for')?> <?php echo $row->getUserName() ?>"
                             title="<?php echo $this->__('Avatar for')?> <?php echo $row->getUserName() ?>"
                             class="avatar"/>
                    <?php else:?>
                        <?php echo $this->gravatar($row->email, array(), array('title' => $this->__('Avatar for') . ' '  . ($row->getUserName()), 'class' => 'avatar'))?>
                    <?php endif;?>
                    
                    
                    <article class="comment" id="comment-1">
                        <?php echo ucfirst($row->login)?> <?php echo $this->__('on')?> <?php echo $this->date($row->created)?>
                        <span class="says"><?php echo $this->__('said')?>:</span>

                        <p><?php echo $row->body ?></p>
                        
                        <div>
                            <input type="button" value="Reply" class="reply" data-commentId="<?php echo $row->id ?>" />
                            <input type="button" value="Subscribe" data-commentId="<?php echo $row->id ?>" />
                        </div>
                    </article>
                </li>
            </ul>
        <?php endforeach;?>
    </div>
<?php endif;?>

<?php $user = $this->user();?>


    <ul class="commentlist">
        <li class="comment">
        <?php if ($user):?>
            <?php if ($user->avatar):?>
                <img src="<?php echo $this->baseUrl($user->avatar)?>" title="<?php echo $this->__('Avatar for')?> <?php echo $user->login?>" class="avatar"/>
            <?php else: ?>
                <?php echo $this->gravatar($user->email, array(), array('title' => $this->__('Avatar for') . ' '  . $user->getName(), 'class' => 'avatar')) ?>
            <?php endif?>
        <?php else : ?>
                <div class="unknown-user"></div>
        <?php endif;?>
       
        <?php echo $this->form;?>
        </li>
    </ul>

<div style="display: none;">
    <div id="commentsLoginForm">
        <?php echo $this->loginForm ?>

        <p class="small">
            <a href="<?php echo $this->url(array('module' => 'users', 'controller' => 'login', 'action' => 'oauth', 'type' => 'twitter'));?>">
            <img src="<?php echo $this->baseUrl('/layouts/default/css/images/twitter-darker.png')?>" alt="<?php echo $this->__('Sign in with Twitter')?>"/>
            </a> |
            <?php echo $this->fbConnect()->login(
                $this->__('Login with Facebook'),
                array('email', 'user_checkins'),
                'onConnect()'
            );?>
        </p>
    </div>
</div>