<?php if ($this->message) : ?>
<h1><?php echo $this->message ?></h1>
<?php else: ?>
<h1><?php $this->_e('The page you are searching, not found.') ?></h1>
<?php endif; ?>

<?php if (Zend_Controller_Front::getInstance()->getParam('displayExceptions')): ?>
<h3>Exception information:</h3>
<p>
  <b>Message:</b> <?php echo $this->exception->getMessage() ?>
</p>

<h3>Stack trace:</h3>
<pre>
<?php echo $this->exception->getTraceAsString() ?>
</pre>

<h3>Request Parameters:</h3>
<pre>
<?php print_r($this->request->getParams()) ?>
</pre>
<?php endif ?>