<h2><?php echo $this->__('Can not create config file')?></h2>
<hr/>
<article>
    <p class="alert alert-info">
        To create a configuration file, the directory in which it is located, should have the right to write
        <code><?php echo 'chmod 777 ' . APPLICATION_PATH . '/configs/';?></code>
    </p>
    <p class="alert">
        <?php echo $this->__('Paste following code into configuration file')?>:
        <br/>
        <code><?php echo $this->filename?></code>
        <br/><br/>
        <textarea class="input-xxlarge" style="width:100%" rows="24" cols="52"><?php echo $this->config?></textarea>

    </p>

    <p class="alert alert-info">
        <?php echo $this->__('And remove module Install')?>:
        <br/>
        <?php if(DIRECTORY_SEPARATOR == '/'): ?>
            <code><?php echo 'rm -r ' . APPLICATION_PATH . '/modules/install/';?></code>
        <?php else: ?>
            <code><?php echo 'del ' . APPLICATION_PATH . '\modules\install\\';?></code>
        <?php endif; ?>
    </p>
</article>
<a href="<?php echo $this->baseUrl('/') ?>" title="<?php echo $this->__('Finish')?>" class="btn btn-primary pull-right"><?php echo $this->__('Finish')?></a>