<h2 class="clear"><?php echo $this->__('Mandatory requirements')?>:</h2>

<h4><?php echo $this->__('PHP version')?>:</h4>

<ul>
    <li>
        <p class="<?php echo $this->isValidPhpVersion? 'acceptIcon' : 'noAcceptIcon'; ?>">Checking that PHP version is at least 5.2.4 (<?php echo $this->phpversion;?> installed)</p>
    </li>
</ul>
<h4><?php echo $this->__('Directories')?>:</h4>

<ul>
    <?php
     foreach ($this->folders as $folder):?>
    <li>
        <?php
        if (!isset($this->unwritable[$folder])) {
            echo '<p class="acceptIcon">Checking that `' . $folder .'` is writable</p>';
        } else {
            echo '<p class="noAcceptIcon">Checking that `' . $folder .'` is writable <span class="recomendations">'
                . $this->__('Run `chmod 777 ' . realpath($this->unwritable[$folder]) . '`') . '</span>';
        }
        ?>

        </li>
    <?php endforeach;?>
</ul>

<h2><?php echo $this->__('Optional checks')?>:</h2>
<h4><?php echo $this->__('PHP configs')?>:</h4>

<ul>
<?php
 foreach ($this->phpOptions as $opt => $value): ?>
    <li>
        <p class="<?php echo ($value['check']) ? 'acceptIcon' : 'warningAcceptIcon'; ?>"><?php echo $value['title']; ?></p>
    </li>
<?php endforeach;?>
</ul>

<h4><?php echo $this->__('PHP extensions')?>:</h4>

<ul>
<?php foreach ($this->phpExtensions as $ext => $desc): ?>
    <li>
        <p class="<?php echo $desc['check'] ? 'acceptIcon' : 'warningAcceptIcon'; ?>"><?php echo $desc['title'];?>
        <span class="recomendations"><?php echo $desc['description'];?></span>
        </p>
    </li>
<?php endforeach;?>
</ul>

<form method="post">
<dl>
    <dd id="submit-element">
    <input type="submit" name="submit" <?php echo $this->isValid ? '' : 'disabled';?> id="submit" value="Next &gt;"></dd>
</dl>
</form>













