<?php

$this->dojo()->addStyleSheet($this->dojo()->getCdnBase() . $this->dojo()->getCdnVersion() . '/dojox/grid/resources/tundraGrid.css')
             ->requireModule('core.grid.Scaffold')
             ->onLoadCaptureStart();
?>
function(){
    // types of data grid
    var typeGrid = {
        dataGrid     : "DataGrid",
        enhancedGrid : "EnhancedGrid"
    };

    var cells = [
    {
        name: "<?php $this->_e('ID')?>",
        field: "id",
        width:'20px'
    },
    {
        name: "<?php $this->_e('Sender')?>",
        field: "sender",
        width:'auto'
    },
    {
        name: "<?php $this->_e('Email')?>",
        field: "email",
        width:'auto'
    },
    {
        name: "<?php $this->_e('Subject')?>",
        field: "subject",
        width:'auto'
    },
    {
        name: "<?php $this->_e('Status')?>",
        field: "status",
        width:'40px'
    },
    {
        name: "<?php $this->_e('Date create')?>",
        field: "created",
        width:'60px'
    },
    {
        name: "<?php $this->_e('Date update')?>",
        field: "updated",
        width:'60px'
    }
    ];
    
    var datagrid = new core.grid.Scaffold(cells,
                                          'gridContainer',
                                          '<?php echo $this->url();?>',
                                          false,
                                          true,
                                          false,
                                          typeGrid.dataGrid);
    //onButtonSubmit();
}
<?php
$this->dojo()->onLoadCaptureEnd();

$this->javascript()->controller();
?>
<form id="feedbackForm" 
      name="feedbackForm" 
      method="post" 
      action="<?php echo $this->url();?>"
      enctype="application/x-www-form-urlencoded"
>
<div class="gridControl">
<?php
    echo $this->comboBox('grid-field', 
                         null,
                         array('jsid' => 'grid-field', 'autocomplete' => false),
                         array(), 
                         array('sender'      => $this->__('Sender'),
                               'email'       => $this->__('Email'),
                               'subject'     => $this->__('Subject'),
                               'status'      => $this->__('Status'),
                               'created'     => $this->__('Date create'),
                               'updated'     => $this->__('Date update')
                              )
                        );
    echo $this->validationTextBox('grid-filter',
                                  '*',
                                  array('jsid'     => 'grid-filter',
                                        'regExp'   => '[\S\s]+',
                                        'required' => 'true'),
                                  array('style' => 'padding:2px 1px 1px')
                                  );
                                                 
    echo $this->button('grid-search', 
                       $this->__('Filter'), 
                       array('jsid'      => 'grid-search',
                             'baseClass' => 'gridButton'));
    echo $this->button('grid-undo', 
                       $this->__('Undo'), 
                       array('jsid'      => 'grid-undo',
                             'baseClass' => 'gridButton'));
?>
</div>

<div class="gridContainer" id="gridContainer" style="height:300px;"></div>

<div class="gridControl">
<?php
/*
    echo $this->comboBox('grid-status', 
                         null, 
                         array('jsid' => 'grid-status','autocomplete' => false, 'required' => true), 
                         array(),
                         array(
                             Feedback_Model_Feedback::STATUS_READ   => Feedback_Model_Feedback::STATUS_READ,
                             Feedback_Model_Feedback::STATUS_REPLY  => Feedback_Model_Feedback::STATUS_REPLY,
                             Feedback_Model_Feedback::STATUS_EDIT   => Feedback_Model_Feedback::STATUS_EDIT,
                             Feedback_Model_Feedback::STATUS_DELETE => Feedback_Model_Feedback::STATUS_DELETE,
                         )
    );
    echo $this->submitButton('grid-submit', 
                             $this->__('Submit'), 
                             array('jsid'      => 'grid-submit',
                                   'baseClass' => 'gridButton'));
*/
    echo $this->formHidden('viewForm', '1');
    echo $this->formHidden('id', '');

?>
</div>
</form>