<div id="formRead">
    <dl>
        <dt class="label subject"><?php echo $this->__('Subject') ?></dt>
        <dd class="value subject"><?php echo $this->mail->subject; ?></dd>

        <dt class="label sender"><?php echo $this->__('Sender')  ?></dt>
        <dd class="value sender"><?php echo $this->mail->sender;  ?></dd>

        <dt class="label email"><?php echo $this->__('Email')   ?></dt>
        <dd class="value email"><?php echo $this->mail->email; ?></dd>

        <dt class="label body"><?php echo $this->__('Body')    ?></dt>
        <dd class="value body"><?php echo $this->mail->message; ?></dd>
    </dl>
</div>

<br />

<h3><?php echo $this->__('Reply')?></h3>
<div id="formReply">
    <?php echo $this->form;?>
</div>
